# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_thumbnail_pb2 as video__thumbnail__pb2


class VideoStub(object):
    """Service to perform video thumbnailing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.stream_stream(
                '/video_thumbnail.Video/Process',
                request_serializer=video__thumbnail__pb2.VideoCandidate.SerializeToString,
                response_deserializer=video__thumbnail__pb2.VideoResult.FromString,
                )


class VideoServicer(object):
    """Service to perform video thumbnailing
    """

    def Process(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.stream_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=video__thumbnail__pb2.VideoCandidate.FromString,
                    response_serializer=video__thumbnail__pb2.VideoResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_thumbnail.Video', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Video(object):
    """Service to perform video thumbnailing
    """

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/video_thumbnail.Video/Process',
            video__thumbnail__pb2.VideoCandidate.SerializeToString,
            video__thumbnail__pb2.VideoResult.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
