# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_thumbnail.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_thumbnail.proto',
  package='video_thumbnail',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15video_thumbnail.proto\x12\x0fvideo_thumbnail\"\x1f\n\x0eVideoCandidate\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"+\n\x0bVideoResult\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\x32W\n\x05Video\x12N\n\x07Process\x12\x1f.video_thumbnail.VideoCandidate\x1a\x1c.video_thumbnail.VideoResult\"\x00(\x01\x30\x01\x62\x06proto3'
)




_VIDEOCANDIDATE = _descriptor.Descriptor(
  name='VideoCandidate',
  full_name='video_thumbnail.VideoCandidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='video_thumbnail.VideoCandidate.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=73,
)


_VIDEORESULT = _descriptor.Descriptor(
  name='VideoResult',
  full_name='video_thumbnail.VideoResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='video_thumbnail.VideoResult.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='video_thumbnail.VideoResult.chunk', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['VideoCandidate'] = _VIDEOCANDIDATE
DESCRIPTOR.message_types_by_name['VideoResult'] = _VIDEORESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoCandidate = _reflection.GeneratedProtocolMessageType('VideoCandidate', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOCANDIDATE,
  '__module__' : 'video_thumbnail_pb2'
  # @@protoc_insertion_point(class_scope:video_thumbnail.VideoCandidate)
  })
_sym_db.RegisterMessage(VideoCandidate)

VideoResult = _reflection.GeneratedProtocolMessageType('VideoResult', (_message.Message,), {
  'DESCRIPTOR' : _VIDEORESULT,
  '__module__' : 'video_thumbnail_pb2'
  # @@protoc_insertion_point(class_scope:video_thumbnail.VideoResult)
  })
_sym_db.RegisterMessage(VideoResult)



_VIDEO = _descriptor.ServiceDescriptor(
  name='Video',
  full_name='video_thumbnail.Video',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=120,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='Process',
    full_name='video_thumbnail.Video.Process',
    index=0,
    containing_service=None,
    input_type=_VIDEOCANDIDATE,
    output_type=_VIDEORESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIDEO)

DESCRIPTOR.services_by_name['Video'] = _VIDEO

# @@protoc_insertion_point(module_scope)
